<div style="padding:30px; color: white; background-color: #0071CD">
<center>
<img src="img/logoub.jpeg"></img>
<center>
<p>
<h1>Algorísmica Avançada</h1>
<h2>Práctica 3 - Enumerativos </h2>
</center>
</p>
</div>

<div class="alert alert-info">
<center>
  <h1>Introducción</h1>
</center>
</div>

En ésta práctica utilizaremos el concepto de ramificación y poda para la resolución del siguiente problema.

La construcción de un artefacto requiere ensamblar $M$ piezas que identificamos con números entre $1$ y $M$. El coste de ensamblar la pieza $i$ depende del número de piezas ya ensambladas. Los costes, que son valores positivos, se nos proporcionan en una matriz $C$. La celda $c_{ij}$ es el coste de ensamblar la pieza $i$ cuando ya se han ensamblado $j$ piezas. Deseamos calcular el orden de ensamblado de menor coste total, entendido éste como la suma del coste de ensamblaje de cada una de las piezas. 

<div class="alert alert-info">
<center>
  <h1>Contenido</h1>
  </center><p>
    </p></div>




<div class="alert alert-success" style="width:90%; margin:0 auto;">
  <h2><p>Ramificación y poda: Problema del ensamblaje</p></h2>
  
  <div class="row">
  <div>
  <p style="text-align: justify; padding-right: 30px">
  Implementa mediante ramificación y poda una solución al problema del ensamblaje con tal de encontrar el listado ordenado de piezas cuyo coste total de ensamblaje sea mínimo.
  </p>
  </div>
    </div></div>


<div class="alert alert-danger" style="width:80%; margin:0 auto; padding">
<center><p><h3> Código </h3></p> </center> 

<p>
<h3>INPUT</h3>
<ul>
<li>C: Matriz de costes de tamaño $M\times M$, donde M es el número de piezas. El elemento $i,j$ de la matriz representa el coste de ensamblaje para la pieza $i$ tras haber colocado $j$ piezas. 
</li>
</ul>
<br>
<h3>OUTPUT</h3>
Lista de números de $1$ a $M$ ordenados de forma que el coste total de ensamblaje sea mínimo. Ej: [5, 3, 2, 4, 1]
</p>

</div>

In [ ]:

Solucion encontrada(ELEMENTO NEUTRO)
FUNCION OBJETIVO

ESTADOS COMPLETO FACTIBLE

SOLUCION

CRITERIO DE RAMIFICACION
CRITERIO DE PODA

COTAS OPTIMISTA Y PESIMISTA

MEJOR LA OPTIMISTA Y HACER UNA FUNCIÓN PARA ELLO

SI LA SOLUCION ES MEJOR A LA OPTIMISTA NO VAMOS A NINGUNA PARTE

COGER EL MINIMO

CRITERIO DE EXPLORACION

EXPANDED (CUANTOS ESTADOS HEMOS PROBADO)


In [56]:
import numpy as np
import heapq
from heapq import heappush, heappop
import copy

def branch_bound(C):
    
    estructura = [] #Inicializamos una lista dónde esta la cota optimista,la solución parcial, valor, cota pesimista y contObj
    
    expanded = 0
    solu = []# Aquí se guardará la cota superior
   
 
    for i in range (len(C)): #Recorremos toda la matriz
        contObj = [i for i in range(0,len(C))] #contObj esta formmado por los componentes de la matriz
        contObj.remove(i) #Va quitando los componentes
        heappush(estructura,[C[i][0],[i],contObj]) #Añade a estructura
        
    #print(estructura)
    for x in range(len(C)): #Recorremos la matriz para hacer la cota supperior mediante la diagonal(cota superior)
            solu.append(x)
    traza = C.trace()
    solu.append([traza])
    print(solu)
    
    while (estructura[0][0] < traza): #Mientras que la cota optimista sea menor a la tarza
        aux = heappop(estructura) #Va removiendo aux en estructura
        expanded += 1
        #print(aux)
        for f in (aux[2]): #Recorre contObj 
            a = aux[0]+ C[f][len(aux[1])] #Va sumando la longitud  de la solucion parcial con la cota optimista
            b = copy.deepcopy(aux[1]) #Copiamos la solucion parcial
            b.append(f) #Añadimos a la copia de la solucion parcial f
            c = copy.deepcopy(aux[2]) #Copiamos el contObj
            c.remove(f) #Eliminamos de la copia de contObj f
            heappush(estructura,[a,b,c]) #Añadimos a estructura a,b y c
        if (len(aux[1]) == len(C) and aux[0] < traza): #Si la longitud de la solucion es igual a la de la matriz finaliza el programa        
             #Si la cota optimista es menor a traza
                traza = aux[0] #Igualamos traza a cota optimista y damos por finalizado el programa                
    return aux,expanded

In [58]:
import random as rd
import numpy as np
import timeit

M = 10 # Número de piezas 10
# Matriz de costes generada aleatoriamente
C = np.zeros((M,M))
rd.seed(1)
for i in range(M):
    for j in range(M):
        C[i][j] = rd.randint(1, 25)
print(C)
start = timeit.default_timer()
solucion = branch_bound(C)
end = timeit.default_timer()
print("Temps: ",end-start)
print(solucion)

[[  5.  19.  25.   3.   9.   4.  16.  25.  15.  16.]
 [ 21.  13.   7.   4.  16.   1.  13.  14.  20.  25.]
 [ 25.   1.  23.  15.   9.  24.   8.  19.   4.  11.]
 [  1.   1.   1.  21.  18.   1.  13.  22.   7.  14.]
 [ 24.   1.  17.   8.  25.  15.  16.  18.   8.  12.]
 [  8.  22.   8.  25.  15.  10.   1.  14.  18.  21.]
 [  4.   6.  21.  24.  10.   4.  24.  11.  24.  23.]
 [ 17.  14.  17.  22.   7.  10.  10.  19.  16.  17.]
 [ 13.  19.   2.  16.   8.  24.  13.  14.  22.   6.]
 [ 12.  18.  23.  25.  22.  24.  12.   3.  15.  22.]]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, [184.0]]
Temps:  0.12966965156238075
([31.0, [6, 4, 3, 0, 7, 1, 5, 9, 2, 8], []], 2270)


<div class="alert alert-danger" style="width:80%; margin:0 auto; padding">
<center><p><h3> Comentarios </h3></p> </center> 

</div>

### En esta sección debéis responder a las preguntas siguientes:
#### 1. Explica cómo has realizado tu implementación, enfatizando en la heurística empleada.
#### 2. Análisis de complejidad de la implementación

In [1]:
En el peor de los casos es recorrer todos los nodos posibles

La complejidad de este algoritmo de ramificación y poda es O(n!), ya que vamos desarrollando por todos los objetos 
que podemos ir ensamblando, y en eso influye la cantidad de cada uno de ellos. Aunque sea de un orden factorial su 
complejidad, a la practica una vez encontramos una solución parcial(es hoja y el valor es menor que el de la cota),
podaremos con al condicion decla cota optimista.La última solución parcial, será la solución FINAL.

Mejor caso M

SyntaxError: invalid syntax (<ipython-input-1-df45923dc81c>, line 1)

<div class="alert alert-info">
<center>
  <h1>Entrega</h1>
</center>

<p>
La entrega tiene que consistir en un solo fichero **.ipynb** con el nombre: *Apellido1_Apellido2*_*Nombre*_ASS3.ipyn
</p>
</div>